<?xml version="1.0"?>

<robot
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:xacro="http://www.ros.org/wiki/xacro"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

		<xacro:property name="quadCamBaseRadius" value="0.01" />
		<xacro:property name="quadCamBaseHeight" value="0.01" />

		<xacro:property name="quadCamLensRadius" value="0.005" />
		<xacro:property name="quadCamLensHeight" value="0.005" />

	<!-- GENERAL MACROS -->
	<xacro:property name="PI"       value="3.141592653589793" />
	<xacro:property name="HALF_PI"  value="1.570796326794897" />

  <xacro:macro name="quad_camera" params="parent *origin">
    <joint name="quad_camera_mount_joint" type="fixed">
        <insert_block name="origin" /> 
        <parent link="${parent}"/>
        <child link="quad_camera_link"/>
				<joint_properties damping="0.0" friction="0.0" />
    </joint>

		<link name="quad_camera_link" type="fixed">
        <inertial>
            <mass value="0.001"/>
            <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 ${-quadCamBaseHeight/2}" rpy="0 ${PI/2} 0" />
            <geometry>
                <cylinder radius="${quadCamBaseRadius}" length="${quadCamBaseHeight}"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0 0 ${-quadCamBaseHeight/2}" rpy="0 ${PI/2} 0" />
            <geometry>
                <cylinder radius="${quadCamBaseRadius}" length="${quadCamBaseHeight}"/>
            </geometry>
        </collision>
    </link>

    <link name="quad_camera_lens_link" type="fixed">
        <inertial>
            <mass value="0.001"/>
            <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        
        <visual>
            <origin xyz="${-quadCamLensHeight} 0 ${-quadCamLensHeight}" rpy="0 ${PI/2} 0"/>
            <geometry>
                <cylinder radius="${quadCamLensRadius}" length="${quadCamLensHeight}"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="${-quadCamLensHeight} 0 ${-quadCamLensHeight}" rpy="0 ${PI/2} 0"/>
            <geometry>
                <cylinder radius="${quadCamLensRadius}" length="${quadCamLensHeight}"/>
            </geometry>
        </collision>
    </link>

    <joint name="quad_camera_base_joint" type="fixed" >
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="quad_camera_link" />
        <child link="quad_camera_lens_link"/>
        <joint_properties damping="0.0" friction="0.0" />
    </joint>

   <gazebo reference="quad_camera_link">
      <sensor:camera name="base_link_camera_sensor">
        <imageSize>640 480</imageSize>
        <imageFormat>R8G8B8</imageFormat>
        <hfov>45</hfov>
        <nearClip>0.01</nearClip>
        <farClip>100</farClip>
        <updateRate>30</updateRate>
        <controller:labrob_gazebo_camera name="base_link_camera_controller" plugin="liblabrob_gazebo_camera.so">
	  <cameraName>camera</cameraName>
	  <setNamespace>true</setNamespace>
          <alwaysOn>true</alwaysOn>
          <updateRate>30</updateRate>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>quad_camera_lens_link</frameName>
          <interface:camera name="base_link_camera_iface" />
        </controller:labrob_gazebo_camera>
      </sensor:camera>
      <turnGravityOff>false</turnGravityOff>
      <!--<material>PR2/Blue</material>-->
    </gazebo>

	<gazebo reference="quad_camera_link">
      <material>Gazebo/Yellow</material>
  </gazebo>

  <gazebo reference="quad_camera_lens_link">
      <material>Gazebo/Red</material>
  </gazebo>

	</xacro:macro>
</robot>
