/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class SpeechList implements lcm.lcm.LCMEncodable
{
    public int length;
    public lcmtypes.Speech results[];
 
    public SpeechList()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0231bd272a5561f9L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.SpeechList.class))
            return 0L;
 
        classes.add(lcmtypes.SpeechList.class);
        long hash = LCM_FINGERPRINT_BASE
             + lcmtypes.Speech._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.length); 
 
        for (int a = 0; a < this.length; a++) {
            this.results[a]._encodeRecursive(outs); 
        }
 
    }
 
    public SpeechList(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public SpeechList(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.SpeechList _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.SpeechList o = new lcmtypes.SpeechList();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.length = ins.readInt();
 
        this.results = new lcmtypes.Speech[(int) length];
        for (int a = 0; a < this.length; a++) {
            this.results[a] = lcmtypes.Speech._decodeRecursiveFactory(ins);
        }
 
    }
 
    public lcmtypes.SpeechList copy()
    {
        lcmtypes.SpeechList outobj = new lcmtypes.SpeechList();
        outobj.length = this.length;
 
        outobj.results = new lcmtypes.Speech[(int) length];
        for (int a = 0; a < this.length; a++) {
            outobj.results[a] = this.results[a].copy();
        }
 
        return outobj;
    }
 
}

