/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class TextToSpeechMsg implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public String text;
    public int id;
    public boolean overridable;
 
    public TextToSpeechMsg()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9615529fd2bd3bb2L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.TextToSpeechMsg.class))
            return 0L;
 
        classes.add(lcmtypes.TextToSpeechMsg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.timestamp); 
 
        __strbuf = new char[this.text.length()]; this.text.getChars(0, this.text.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.id); 
 
        outs.writeByte( this.overridable ? 1 : 0); 
 
    }
 
    public TextToSpeechMsg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public TextToSpeechMsg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.TextToSpeechMsg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.TextToSpeechMsg o = new lcmtypes.TextToSpeechMsg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.timestamp = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.text = new String(__strbuf);
 
        this.id = ins.readInt();
 
        this.overridable = ins.readByte()!=0;
 
    }
 
    public lcmtypes.TextToSpeechMsg copy()
    {
        lcmtypes.TextToSpeechMsg outobj = new lcmtypes.TextToSpeechMsg();
        outobj.timestamp = this.timestamp;
 
        outobj.text = this.text;
 
        outobj.id = this.id;
 
        outobj.overridable = this.overridable;
 
        return outobj;
    }
 
}

